import classNames from 'classnames'
import styles from './colours.css'

export default ({
  textBlue, textBlueDark, textGreyBlue, textGrey, textGreyDark, textRed, textGreen,
  textOffWhite, textWhite, textTransparent, fillBlue, fillBlueDark, fillGreyBlue, fillGrey,
  fillGreyDark, fillRed, fillGreen, fillOffWhite, fillWhite, fillTransparent,
  bgBlue, bgBlueDark, bgGreyBlue, bgGrey, bgGreyDark, bgRed, bgGreen, bgOffWhite, bgWhite,
  bgTransparent, borderBlue, borderBlueDark, borderGreyBlue, borderGrey, borderGreyDark,
  borderRed, borderGreen, borderOffWhite, borderWhite, borderTransparent
  }) => {
  return classNames({
    [styles.textBlue]: textBlue,
    [styles.textBlueDark]: textBlueDark,
    [styles.textGreyBlue]: textGreyBlue,
    [styles.textGrey]: textGrey,
    [styles.textGreyDark]: textGreyDark,
    [styles.textGreyDark]: textGreyDark,
    [styles.textRed]: textRed,
    [styles.textGreen]: textGreen,
    [styles.textOffWhite]: textOffWhite,
    [styles.textWhite]: textWhite,
    [styles.textTransparent]: textTransparent,
    [styles.fillBlue]: fillBlue,
    [styles.fillBlueDark]: fillBlueDark,
    [styles.fillGreyBlue]: fillGreyBlue,
    [styles.fillGrey]: fillGrey,
    [styles.fillGreyDark]: fillGreyDark,
    [styles.fillRed]: fillRed,
    [styles.fillGreen]: fillGreen,
    [styles.fillOffWhite]: fillOffWhite,
    [styles.fillWhite]: fillWhite,
    [styles.fillTransparent]: fillTransparent,
    [styles.bgBlue]: bgBlue,
    [styles.bgBlueDark]: bgBlueDark,
    [styles.bgGreyBlue]: bgGreyBlue,
    [styles.bgGrey]: bgGrey,
    [styles.bgGreyDark]: bgGreyDark,
    [styles.bgRed]: bgRed,
    [styles.bgGreen]: bgGreen,
    [styles.bgOffWhite]: bgOffWhite,
    [styles.bgWhite]: bgWhite,
    [styles.bgTransparent]: bgTransparent,
    [styles.borderBlue]: borderBlue,
    [styles.borderBlueDark]: borderBlueDark,
    [styles.borderGreyBlue]: borderGreyBlue,
    [styles.borderGrey]: borderGrey,
    [styles.borderGreyDark]: borderGreyDark,
    [styles.borderRed]: borderRed,
    [styles.borderGreen]: borderGreen,
    [styles.borderOffWhite]: borderOffWhite,
    [styles.borderWhite]: borderWhite,
    [styles.borderTransparent]: borderTransparent,
  })
}
